export interface Term {
  term: string;
  definition: { ar: string; en: string };
  category: "attack" | "defense" | "crypto" | "cloud" | "ad" | "web" | "general";
}

export const GLOSSARY: Term[] = [
  // Attack
  { term: "APT", category: "attack",
    definition: { ar: "Advanced Persistent Threat — تهديد متقدم مستمر، غالباً ما يكون برعاية دولة، ويتميز بالقدرة على البقاء داخل الشبكات لفترات طويلة بهدف التجسس أو التخريب الاستراتيجي.",
                  en: "Advanced Persistent Threat — a sophisticated, often state-sponsored adversary that operates over months or years." } },
  { term: "C2 / Command & Control", category: "attack",
    definition: { ar: "نظام التحكم والسيطرة — البنية التحتية التي يستخدمها المهاجم لإرسال الأوامر للأجهزة المخترقة واستقبال البيانات المسربة منها.",
                  en: "Channel between the attacker and the compromised host for sending commands and receiving data." } },
  { term: "Reverse Shell", category: "attack",
    definition: { ar: "القشرة العكسية — نوع من الاتصال يبدأ من جهاز الضحية باتجاه المهاجم، ويُستخدم عادةً للالتفاف على قيود جدران الحماية التي تمنع الاتصالات الواردة.",
                  en: "An outbound connection from the victim to the attacker, used to bypass firewalls." } },
  { term: "Lateral Movement", category: "attack",
    definition: { ar: "التحرك الجانبي — التكتيكات التي يستخدمها المهاجم للتنقل من جهاز إلى آخر داخل الشبكة بحثاً عن الأصول الحيوية بعد نجاح الاختراق الأولي.",
                  en: "Moving from one host to another inside the network after initial compromise." } },
  { term: "Persistence", category: "attack",
    definition: { ar: "الاستمرارية — الآليات التي يزرعها المهاجم داخل النظام لضمان الاحتفاظ بمدخل نفاذ دائم حتى بعد إعادة تشغيل الجهاز أو تغيير كلمات المرور.",
                  en: "Mechanisms that let the attacker return after a reboot." } },
  { term: "Privilege Escalation", category: "attack",
    definition: { ar: "تصعيد الصلاحيات — عملية استغلال ثغرات أو أخطاء تكوين للانتقال من صلاحيات مستخدم محدود إلى صلاحيات كاملة (مثل root أو Administrator).",
                  en: "Moving from a regular-user privilege to root/Administrator." } },
  { term: "Payload", category: "attack",
    definition: { ar: "الحمولة البرمجية — الكود البرمجي المخصص للتنفيذ بمجرد نجاح الثغرة (exploit) في اختراق النظام، مثل أوامر فتح اتصال عكسي أو زرع برمجية تجسس.",
                  en: "The executable code carried by an exploit to run on the target." } },
  { term: "Exploit", category: "attack",
    definition: { ar: "ثغرة استغلال — كود برمجي أو تقنية تستغل عيباً في النظام لإجباره على سلوك غير مقصود، مما يمهد الطريق لنفاذ المهاجم.",
                  en: "Code that abuses a vulnerability to alter system behavior." } },
  { term: "Zero-day (0-day)", category: "attack",
    definition: { ar: "ثغرة اليوم الصفر — ثغرة برمجية مكتشفة حديثاً لم يعلم بها المصنع بعد، وبالتالي لا يتوفر لها أي رقعة أمنية (Patch) أو حل تقني وقت استغلالها.",
                  en: "A vulnerability with no available patch, often unknown to the vendor." } },
  { term: "TTP", category: "attack",
    definition: { ar: "Tactics, Techniques & Procedures — التكتيكات والتقنيات والإجراءات التي تشكل المنهجية السلوكية للمهاجم وتساعد في تحديد هويته وانتمائه.",
                  en: "Tactics, Techniques & Procedures — attacker behavior patterns." } },
  { term: "IOC", category: "attack",
    definition: { ar: "Indicator of Compromise — مؤشر اختراق تقني (مثل عنوان IP مريب أو بصمة ملف خبيث) يدل بوضوح على حدوث انتهاك أمني.",
                  en: "Indicator of Compromise — a technical artifact (IP, hash, domain) signaling intrusion." } },
  { term: "Kill Chain", category: "attack",
    definition: { ar: "سلسلة القتل السيبراني — نموذج يصف المراحل السبع للهجوم المتقدم، بدءاً من الاستطلاع وصولاً إلى تحقيق الأهداف النهائية للهجوم.",
                  en: "Lockheed Martin model describing the 7 stages of an advanced attack." } },
  { term: "Phishing", category: "attack",
    definition: { ar: "التصيد الاحتيالي — استخدام أساليب التلاعب النفسي لخداع المستخدمين للكشف عن بيانات حساسة أو تثبيت برمجيات خبيثة.",
                  en: "Tricking users into giving credentials or running malware via email/message." } },
  { term: "Spear Phishing", category: "attack",
    definition: { ar: "التصيد المُوجّه — حملة تصيد مصممة خصيصاً لاستهداف أفراد أو مؤسسات بعينها بناءً على معلومات تم جمعها مسبقاً لزيادة احتمالية النجاح.",
                  en: "Phishing targeted at a specific person after OSINT." } },
  { term: "BEC", category: "attack",
    definition: { ar: "Business Email Compromise — انتحال هوية المسؤولين التنفيذيين عبر البريد الإلكتروني لخداع الموظفين لإجراء تحويلات مالية غير مصرح بها.",
                  en: "Business Email Compromise — impersonating an executive to issue a financial order." } },
  { term: "Ransomware", category: "attack",
    definition: { ar: "برمجيات الفدية — نوع من البرامج الخبيثة التي تقوم بتشفير بيانات الضحية ومنع الوصول إليها حتى يتم دفع مبالغ مالية مقابل مفتاح التشفير.",
                  en: "Malware that encrypts data and demands ransom for decryption." } },

  // Web
  { term: "SQL Injection (SQLi)", category: "web",
    definition: { ar: "حقن استعلامات SQL — ثغرة تسمح للمهاجم بالتلاعب باستعلامات قاعدة البيانات عبر إدخال أوامر خبيثة في حقول الإدخال الخاصة بالتطبيق.",
                  en: "Injecting malicious SQL via application inputs." } },
  { term: "XSS", category: "web",
    definition: { ar: "حقن النصوص البرمجية (Cross-Site Scripting) — ثغرة تتيح للمهاجم زرع أكواد JavaScript خبيثة تُنفذ في متصفح المستخدمين الآخرين للتطبيق.",
                  en: "Cross-Site Scripting — injected JavaScript executes in another user's browser." } },
  { term: "CSRF", category: "web",
    definition: { ar: "تزوير الطلبات عبر المواقع — هجوم يجبر متصفح المستخدم على تنفيذ إجراءات غير مرغوب فيها في تطبيق ويب يكون المستخدم مسجلاً للدخول فيه.",
                  en: "Cross-Site Request Forgery — forces the user's browser to send a request on their behalf." } },
  { term: "SSRF", category: "web",
    definition: { ar: "تزوير الطلبات من جانب الخادم — ثغرة تجبر خادم التطبيق على إرسال طلبات لجهات داخلية أو خارجية لم يكن من المفترض الوصول إليها.",
                  en: "Server-Side Request Forgery — the server fetches an attacker-controlled URL." } },
  { term: "IDOR / BOLA", category: "web",
    definition: { ar: "الوصول غير المباشر للأهداف — ثغرة تسمح للمستخدم بالوصول إلى بيانات مستخدمين آخرين عبر التلاعب بمعرفات الموارد (مثل تغيير id=123 إلى id=124).",
                  en: "Insecure Direct Object Reference — change an ID to access another user's data." } },
  { term: "RCE", category: "web",
    definition: { ar: "Remote Code Execution — تنفيذ الأوامر البرمجية عن بُعد على النظام المستهدف، وتعتبر من أخطر أنواع الثغرات الأمنية.",
                  en: "Remote Code Execution — running attacker code on the server." } },
  { term: "LFI / RFI", category: "web",
    definition: { ar: "تضمين الملفات (محلياً أو عن بُعد) — ثغرة تسمح للتطبيق بتحميل وتضمين ملفات من خادم محلي أو رابط خارجي بشكل غير آمن.",
                  en: "Local/Remote File Inclusion — including a local or remote file." } },
  { term: "WAF", category: "web",
    definition: { ar: "جدار حماية تطبيقات الويب — نظام أمني مخصص لمراقبة وتصفية حركة مرور HTTP من وإلى تطبيق الويب لمنع الهجمات الشائعة.",
                  en: "Web Application Firewall — filters malicious HTTP requests." } },
  { term: "CSP", category: "web",
    definition: { ar: "سياسة أمن المحتوى — طبقة أمان إضافية تساعد في كشف وتقليل أنواع معينة من الهجمات مثل XSS وحقن البيانات.",
                  en: "Content Security Policy — header that whitelists allowed script/style sources." } },
  { term: "CORS", category: "web",
    definition: { ar: "مشاركة الموارد عبر الأصول المختلفة — آلية تسمح للمتصفحات بمشاركة البيانات بين نطاقات (domains) مختلفة بشكل محكم ومنظم.",
                  en: "Cross-Origin Resource Sharing — controls cross-domain JavaScript requests." } },

  // Defense
  { term: "SIEM", category: "defense",
    definition: { ar: "إدارة الأحداث والمعلومات الأمنية — منصة مركزية لجمع وتحليل السجلات الأمنية من مختلف أجهزة الشبكة للكشف عن التهديدات.",
                  en: "Security Information and Event Management — platform aggregating and analyzing logs." } },
  { term: "EDR / XDR", category: "defense",
    definition: { ar: "أنظمة الكشف والاستجابة لنقاط النهاية — أدوات تركز على مراقبة سلوك الأجهزة والخدمات لاكتشاف التهديدات المتقدمة التي تتجاوز مضادات الفيروسات.",
                  en: "Endpoint/Extended Detection & Response — behavioral monitoring on endpoints." } },
  { term: "SOAR", category: "defense",
    definition: { ar: "أتمتة وتنسيق الاستجابة الأمنية — تقنيات تهدف إلى أتمتة الإجراءات الدفاعية والتعامل السريع مع التنبيهات الأمنية المتكررة.",
                  en: "Security Orchestration, Automation and Response — automating security playbooks." } },
  { term: "DLP", category: "defense",
    definition: { ar: "منع تسريب البيانات — استراتيجيات وأدوات تقنية تهدف إلى ضمان عدم إرسال البيانات الحساسة خارج الشبكة المؤسسية بشكل غير مصرح به.",
                  en: "Data Loss Prevention — blocking data exfiltration." } },
  { term: "Honeypot / Honeytoken", category: "defense",
    definition: { ar: "المصيدة / الرمز الفخ — أنظمة أو بيانات وهمية تُنشر في الشبكة لجذب المهاجمين وكشف وجودهم فور التفاعل معها.",
                  en: "A fake system or file used to lure attackers." } },
  { term: "Sigma", category: "defense",
    definition: { ar: "لغة سيجما — معيار موحد لكتابة قواعد الكشف الأمني بشكل مستقل عن نوع المنصة المستخدمة (مثل Splunk أو Sentinel).",
                  en: "A vendor-neutral format for detection rules across SIEMs." } },
  { term: "YARA", category: "defense",
    definition: { ar: "قواعد يارا — أداة تستخدم لتصنيف والتعرف على عينات البرمجيات الخبيثة بناءً على أنماط النصوص أو البيانات الثنائية داخلها.",
                  en: "A language to describe byte/string patterns matching malware families." } },
  { term: "Sysmon", category: "defense",
    definition: { ar: "أداة مراقبة النظام — خدمة من ويندوز توفر سجلات تفصيلية حول العمليات النشطة، واتصالات الشبكة، والتغييرات في الملفات.",
                  en: "Microsoft tool logging deep Windows events (process, network, registry)." } },
  { term: "MITRE ATT&CK", category: "defense",
    definition: { ar: "إطار مايتر أتاك — قاعدة معرفية عالمية توثق تكتيكات وتقنيات المهاجمين بناءً على ملاحظات واقعية من الهجمات السيبرانية.",
                  en: "Knowledge base of documented adversary tactics and techniques." } },
  { term: "Threat Hunting", category: "defense",
    definition: { ar: "التقصي النشط عن التهديدات — عملية البحث الاستباقي واليدوي داخل الشبكة عن آثار المهاجمين الذين نجحوا في تجاوز أنظمة الكشف الآلية.",
                  en: "Proactive search for compromise artifacts that automated detection missed." } },
  { term: "DFIR", category: "defense",
    definition: { ar: "التحقيق الجنائي الرقمي والاستجابة للحوادث — العلم الذي يجمع بين جمع الأدلة الرقمية والتعامل الفوري مع الهجمات النشطة.",
                  en: "Digital Forensics & Incident Response." } },
  { term: "IR Playbook", category: "defense",
    definition: { ar: "دليل الاستجابة — مجموعة من الإجراءات والخطوات المحددة مسبقاً للتعامل مع أنواع معينة من الحوادث الأمنية بفعالية.",
                  en: "An approved step-by-step response document per incident type." } },

  // Crypto
  { term: "AES", category: "crypto",
    definition: { ar: "معيار التشفير المتقدم — أقوى خوارزميات التشفير التماثلي المعتمدة عالمياً لحماية البيانات الحساسة.",
                  en: "Advanced Encryption Standard — the standard symmetric encryption algorithm." } },
  { term: "AEAD", category: "crypto",
    definition: { ar: "التشفير الموثق مع البيانات المصاحبة — تقنية توفر التشفير وضمان سلامة البيانات في آن واحد لمنع التلاعب بالرسائل المشفرة.",
                  en: "Authenticated Encryption with Associated Data — combines encryption and integrity." } },
  { term: "RSA / ECC", category: "crypto",
    definition: { ar: "خوارزميات التشفير غير التماثلي؛ حيث توفر ECC أماناً مكافئاً لـ RSA مع مفاتيح أصغر بكثير وأداء أسرع.",
                  en: "Asymmetric crypto algorithms. ECC is smaller and faster for the same security level." } },
  { term: "PKI", category: "crypto",
    definition: { ar: "البنية التحتية للمفاتيح العامة — منظومة متكاملة من البرمجيات والسياسات تهدف إلى إصدار وإدارة وتوزيع الشهادات الرقمية.",
                  en: "Public Key Infrastructure — the system that issues and manages certificates." } },
  { term: "TLS", category: "crypto",
    definition: { ar: "أمن طبقة النقل — البروتوكول الأمني الذي يوفر تشفيراً لاتصالات الشبكة، وهو التطور الحديث لبروتوكول SSL.",
                  en: "Transport Layer Security — the protocol behind HTTPS encryption." } },
  { term: "JWT", category: "crypto",
    definition: { ar: "رموز جيسون للويب — معيار مفتوح لمشاركة البيانات الموقعة رقمياً بين جهتين بشكل آمن وموثوق.",
                  en: "JSON Web Token — a digitally signed token carrying claims." } },
  { term: "HSM / KMS", category: "crypto",
    definition: { ar: "وحدة الأمان العتادية / خدمة إدارة المفاتيح — تقنيات مخصصة لتخزين مفاتيح التشفير وإجراء العمليات الحسابية داخل بيئة فيزيائية محصنة.",
                  en: "Hardware Security Module / Key Management Service — secure key storage." } },
  { term: "Argon2id", category: "crypto",
    definition: { ar: "خوارزمية أرجون 2 — تعتبر المعيار العالمي الأحدث والأكثر أماناً لتجزئة كلمات المرور وحمايتها من هجمات الكسر بالقوة الغاشمة.",
                  en: "The recommended password hashing algorithm in 2026." } },

  // AD
  { term: "Domain Controller (DC)", category: "ad",
    definition: { ar: "متحكم النطاق — الخادم المسؤول عن إدارة قاعدة بيانات Active Directory والمصادقة على هويات المستخدمين داخل الشبكة.",
                  en: "The server that runs Active Directory and authenticates users." } },
  { term: "Kerberos", category: "ad",
    definition: { ar: "بروتوكول كيربيروس — بروتوكول المصادقة الرئيسي في بيئات ويندوز، ويعتمد على نظام التذاكر (Tickets) لضمان الأمان.",
                  en: "Windows' primary auth protocol (TGT, TGS tickets)." } },
  { term: "Kerberoasting", category: "ad",
    definition: { ar: "هجوم كيربيروستينغ — تقنية تستهدف الحصول على تذاكر الخدمات (TGS) لكسر تشفيرها لاحقاً واستخراج كلمات مرور حسابات الخدمات.",
                  en: "Request a TGS for an SPN-bearing account, then crack the signature offline." } },
  { term: "Pass-the-Hash (PtH)", category: "ad",
    definition: { ar: "تمرير الهاش — تكتيك يسمح للمهاجم بالمصادقة على النظام باستخدام بصمة كلمة المرور (Hash) مباشرة دون الحاجة لمعرفة كلمة المرور الأصلية.",
                  en: "Authenticating with an NT hash directly, without cracking the password." } },
  { term: "Golden Ticket", category: "ad",
    definition: { ar: "التذكرة الذهبية — تذكرة TGT مزورة تمنح المهاجم صلاحيات مطلقة ودائمة على نطاق ويندوز بالكامل.",
                  en: "Forged TGT signed with the krbtgt key — full domain power." } },
  { term: "DCSync", category: "ad",
    definition: { ar: "هجوم دي-سي-سينك — تكتيك يحاكي سلوك متحكم النطاق لطلب مزامنة كلمات المرور المشفرة لجميع المستخدمين.",
                  en: "Impersonating a DC to request all domain hashes via replication." } },
  { term: "BloodHound", category: "ad",
    definition: { ar: "أداة بلود-هاوند — أداة تستخدم نظرية المخططات (Graph Theory) للكشف عن مسارات الهجوم الخفية داخل Active Directory.",
                  en: "A tool that maps AD relationships to find the shortest path to Domain Admin." } },
  { term: "ADCS", category: "ad",
    definition: { ar: "خدمات شهادات النطاق — مكون في ويندوز يُستخدم لإصدار الشهادات الرقمية، ويعتبر مصدراً شائعاً لثغرات تصعيد الصلاحيات.",
                  en: "Active Directory Certificate Services — common source of misconfigs (ESC1-ESC15)." } },

  // Cloud
  { term: "IAM", category: "cloud",
    definition: { ar: "إدارة الهوية والوصول — إطار عمل يضمن وصول الأشخاص المناسبين للموارد المناسبة في البيئة السحابية بالصلاحيات الصحيحة.",
                  en: "Identity & Access Management — controls who can do what in the cloud." } },
  { term: "IMDS", category: "cloud",
    definition: { ar: "خدمة بيانات التعريف — واجهة داخلية في السحابة توفر معلومات واعتمادات دخول مؤقتة للخدمات السحابية النشطة.",
                  en: "Instance Metadata Service — internal endpoint that supplies EC2 credentials." } },
  { term: "S3", category: "cloud",
    definition: { ar: "خدمة التخزين البسيط — خدمة تخزين الكائنات من AWS، وغالباً ما يتسبب سوء تكوينها في تسريبات ضخمة للبيانات.",
                  en: "AWS object storage — public buckets are a famous breach source." } },
  { term: "VPC", category: "cloud",
    definition: { ar: "السحابة الخاصة الافتراضية — شبكة منطقية معزولة تمنحك سيطرة كاملة على بيئتك الافتراضية في السحابة.",
                  en: "Virtual Private Cloud — an isolated private network in the cloud." } },
  { term: "CSPM", category: "cloud",
    definition: { ar: "إدارة الحالة الأمنية للسحابة — أدوات تقوم بفحص البيئة السحابية باستمرار للكشف عن أخطاء التكوين والامتثال للمعايير.",
                  en: "Cloud Security Posture Management — automated misconfig detection." } },
  { term: "CIEM", category: "cloud",
    definition: { ar: "إدارة استحقاقات البنية التحتية للسحابة — تقنيات تركز على تحليل وتقليل مخاطر الصلاحيات الزائدة في الهويات السحابية.",
                  en: "Cloud Infrastructure Entitlement Management — analyzing excess IAM permissions." } },
  { term: "Kubernetes (k8s)", category: "cloud",
    definition: { ar: "منصة كوبرنيتيس — نظام مفتوح المصدر لأتمتة نشر وتوسيع وإدارة الحاويات البرمجية (Containers).",
                  en: "Container orchestration platform with its own attack surface (RBAC, kubelet, secrets)." } },

  // General
  { term: "MFA / 2FA", category: "general",
    definition: { ar: "المصادقة المتعددة — أسلوب أمني يتطلب أكثر من دليل لإثبات الهوية قبل السماح بالوصول للنظام.",
                  en: "Multi/Two-Factor Authentication — two or more factors to authenticate." } },
  { term: "FIDO2 / Passkey", category: "general",
    definition: { ar: "مفاتيح المرور — معيار حديث للمصادقة القوية يعتمد على التشفير بالمفاتيح العامة ومحصن تماماً ضد هجمات التصيد.",
                  en: "Domain-bound auth standard, immune to phishing." } },
  { term: "Zero Trust", category: "general",
    definition: { ar: "نموذج الثقة الصفرية — استراتيجية أمنية تقوم على مبدأ 'لا تثق أبداً، وتحقق دائماً' بغض النظر عن موقع المستخدم.",
                  en: "Trust no one, no network — always verify." } },
  { term: "Defense in Depth", category: "general",
    definition: { ar: "الدفاع المتعمق — استراتيجية تعتمد على وضع طبقات أمان متعددة بحيث إذا فشلت إحداها، تقوم الأخرى بصد الهجوم.",
                  en: "Layered security — breaking one layer doesn't compromise the whole." } },
  { term: "Least Privilege", category: "general",
    definition: { ar: "مبدأ الصلاحيات الأقل — ممارسة أمنية تقضي بإعطاء المستخدمين الحد الأدنى من الصلاحيات اللازمة لأداء مهامهم فقط.",
                  en: "Granting the minimum permissions necessary to each user/service." } },
  { term: "SOC", category: "general",
    definition: { ar: "مركز العمليات الأمنية — فريق تقني يعمل على مراقبة وتحليل الحالة الأمنية للمؤسسة والاستجابة للحوادث على مدار الساعة.",
                  en: "Security Operations Center — the team that monitors and responds 24/7." } },
  { term: "CVE / CVSS", category: "general",
    definition: { ar: "قاعدة بيانات الثغرات الشائعة ونظام تقييم خطورتها عالمياً.",
                  en: "Common Vulnerabilities and Exposures + the scoring system." } },
  { term: "OSINT", category: "general",
    definition: { ar: "الاستخبارات مفتوحة المصدر — فن جمع وتحليل المعلومات المتاحة علناً للجمهور لأغراض استخباراتية.",
                  en: "Open Source Intelligence — gathering info from public sources." } },
  { term: "Pentest", category: "general",
    definition: { ar: "اختبار الاختراق — محاكاة لهجوم سيبراني مصرح به لتقييم قوة الأنظمة الدفاعية واكتشاف نقاط الضعف.",
                  en: "Authorized intrusion test to surface vulnerabilities." } },
  { term: "Red / Blue / Purple Team", category: "general",
    definition: { ar: "الفرق الحمراء (الهجوم) والزرقاء (الدفاع) والأرجوانية (التعاون لرفع الكفاءة).",
                  en: "Offensive team / defensive team / collaboration of both." } },
  { term: "MTTD / MTTR", category: "general",
    definition: { ar: "متوسط وقت الكشف والاستجابة — مقاييس أداء تستخدم لتقييم مدى سرعة الفرق الأمنية في التعامل مع التهديدات.",
                  en: "Mean Time To Detect / Respond — team-speed metrics." } },
  { term: "GDPR", category: "general",
    definition: { ar: "اللائحة العامة لحماية البيانات — قانون أوروبي صارم ينظم كيفية جمع ومعالجة البيانات الشخصية للأفراد.",
                  en: "The EU's data protection regulation." } },
  { term: "NIST CSF", category: "general",
    definition: { ar: "إطار الأمن السيبراني NIST — معيار يهدف لتنظيم وتقليل المخاطر السيبرانية التي تواجه المؤسسات الكبرى.",
                  en: "The US cybersecurity framework (Govern, Identify, Protect, Detect, Respond, Recover)." } },
  { term: "ISO 27001", category: "general",
    definition: { ar: "أيزو 27001 — معيار دولي يحدد المتطلبات اللازمة لإنشاء وتطبيق وصيانة نظام إدارة أمن المعلومات.",
                  en: "International standard for an Information Security Management System (ISMS)." } },
];

export const CATEGORIES: Record<string, { ar: string; en: string; chip: string }> = {
  attack:  { ar: "هجوم",        en: "Attack",   chip: "chip chip-red" },
  defense: { ar: "دفاع",        en: "Defense",  chip: "chip chip-blue" },
  web:     { ar: "ويب",         en: "Web",      chip: "chip chip-amber" },
  crypto:  { ar: "تشفير",       en: "Crypto",   chip: "chip chip-green" },
  ad:      { ar: "Active Dir.", en: "Active Dir.", chip: "chip chip-amber" },
  cloud:   { ar: "سحابة",       en: "Cloud",    chip: "chip chip-blue" },
  general: { ar: "عام",         en: "General",  chip: "chip" },
};
